language: python
python:
  - '3.4'
env:
  global:
    - MSCDIR=$TRAVIS_BUILD_DIR/misoc
    - PATH=$HOME/miniconda/bin:/usr/local/llvm-or1k/bin:$PATH
    - CC=gcc-4.7
    - CXX=g++-4.7
    - ARTIQ_NO_HARDWARE=1
    - BUILD_SOC=1
    - secure: "DUk/Ihg8KbbzEgPF0qrHqlxU8e8eET9i/BtzNvFddIGX4HP/P2qz0nk3cVkmjuWhqJXSbC22RdKME9qqPzw6fJwJ6dpJ3OR6dDmSd7rewavq+niwxu52PVa+yK8mL4yf1terM7QQ5tIRf+yUL9qGKrZ2xyvEuRit6d4cFep43Ws="
before_install:
  - if [ $TRAVIS_PULL_REQUEST != false ]; then BUILD_SOC=0; fi
  - ./.travis/get-toolchain.sh
  - if [ $BUILD_SOC -ne 0 ]; then ./.travis/get-xilinx.sh; fi
  - ./.travis/get-anaconda.sh pip coverage binstar
  - source $HOME/miniconda/bin/activate py34
  - sudo apt-get install --force-yes -y iverilog
  - pip install coveralls
  - conda install migen
install:
  - conda build conda/artiq
  - conda install $HOME/miniconda/conda-bld/linux-64/artiq-*.tar.bz2
script:
  - coverage run --source=artiq setup.py test
  - make -C doc/manual html
after_success:
  - binstar login --hostname $(hostname) --username $binstar_login --password $binstar_password
  - binstar upload --user $binstar_login --channel dev --force $HOME/miniconda/conda-bld/linux-64/artiq-*.tar.bz2
  - coveralls
notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d26782523952bfa53814
