[package]
authors = ["M-Labs"]
name = "runtime"
version = "0.0.0"
build = "build.rs"

[lib]
name = "runtime"
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
build_artiq = { path = "../libbuild_artiq" }

[dependencies]
byteorder = { version = "1.0", default-features = false }
cslice = { version = "0.3" }
log = { version = "0.4", default-features = false }
managed = { version = "= 0.7.0", default-features = false, features = ["alloc", "map"] }
alloc_list = { path = "../liballoc_list" }
std_artiq = { path = "../libstd_artiq", features = ["alloc", "io_error_alloc"] }
logger_artiq = { path = "../liblogger_artiq" }
backtrace_artiq = { path = "../libbacktrace_artiq" }
board = { path = "../libboard", features = ["uart_console"] }
proto = { path = "../libproto", features = ["log"] }
amp = { path = "../libamp" }
drtioaux = { path = "../libdrtioaux" }

[dependencies.fringe]
git = "https://github.com/m-labs/libfringe"
rev = "b8a6d8f"
default-features = false
features = ["alloc"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
rev = "92e970b" # NB: also change in libboard_misoc/Cargo.toml
default-features = false
features = ["rust-1.28", "alloc", "log", "proto-ipv4", "socket-tcp"]
