package:
  name: artiq-pipistrello-nist_qc1
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/m-labs/artiq
  git_tag: master

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}

requirements:
  build:
    # We don't get meaningful GIT_DESCRIBE_* values until before conda installs build dependencies.
    - artiq 0.0
    - migen 0.0
    - llvm-or1k
    - binutils-or1k-linux
  run:
    - artiq {{ "{tag} py_{number}+git{hash}".format(tag=environ.get("GIT_DESCRIBE_TAG"), number=environ.get("GIT_DESCRIBE_NUMBER"), hash=environ.get("GIT_DESCRIBE_HASH")[1:]) if "GIT_DESCRIBE_TAG" in environ else "" }}

about:
  home: http://m-labs.hk/artiq
  license: 3-clause BSD
  summary: 'Bitstream, BIOS and runtime for NIST_QC1 on the Pipistrello board'
