package:
  name: artiq-dev
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}

requirements:
  run:
    - python 3.5.2
    - setuptools
    - migen 0.5.dev py_54+git58e8f45
    - misoc 0.6.dev py_4+git40e9940
    - jesd204b 0.2
    - binutils-or1k-linux >=2.27
    - llvm-or1k
    - llvmlite-artiq 0.12.0.dev py35_30
    - rust-core-or1k 1.16.0 11
    - cargo
    - openocd >=0.10
    - lit
    - outputcheck
    - coverage
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - dateutil
    - pyqt5
    - quamash
    - pyqtgraph
    - pygit2
    - aiohttp
    - pythonparser 1.0
    - levenshtein

about:
  home: https://m-labs.hk/artiq
  license: GPL
  summary: 'ARTIQ development metapackage'
