package:
  name: artiq-dev
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}

requirements:
  run:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
    - migen 0.6.dev py35_50+git82b06ee
    - misoc 0.8.dev py35_30+gitd95f4edb
    - jesd204b 0.4
    - binutils-or1k-linux >=2.27
    - llvm-or1k 4.0.1
    - llvmlite-artiq 0.20.0
    - rustc 1.22.1 17
    - rust-core-or1k 1.22.1 18
    - openocd 0.10.0+git1
    - lit
    - outputcheck
    - coverage
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph
    - pygit2
    - aiohttp
    - pythonparser >=1.1
    - levenshtein

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ development metapackage'
