package:
    name: artiq
    version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
    git_url: https://github.com/m-labs/artiq
    git_tag: master

build:
    number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
    entry_points:
        - artiq_client = artiq.frontend.artiq_client:main
        - artiq_compile = artiq.frontend.artiq_compile:main
        - artiq_ctlmgr = artiq.frontend.artiq_ctlmgr:main
        - artiq_master = artiq.frontend.artiq_master:main
        - artiq_rpctool = artiq.frontend.artiq_rpctool:main
        - artiq_run = artiq.frontend.artiq_run:main
        - lda_controller = artiq.frontend.lda_controller:main
        - novatech409b_controller = artiq.frontend.novatech409b_controller:main
        - pdq2_client = artiq.frontend.pdq2_client:main
        - pdq2_controller = artiq.frontend.pdq2_controller:main
        - thorlabs_tcube_controller = artiq.frontend.thorlabs_tcube_controller:main
        - pxi6733_controller = artiq.frontend.pxi6733_controller:main
        - artiq_gui = artiq.frontend.artiq_gui:main # [not win]

requirements:
    build:
        - python
        - setuptools
        - numpy
        - migen
    run:
        - python
        - llvmlite-or1k
        - scipy
        - numpy
        - prettytable
        - pyserial
        - sphinx
        - sphinx-argparse
        - h5py
        - dateutil
        - pydaqmx
        - gbulb-artiq # [not win]
        - cairoplot3-artiq # [not win]

test:
    imports:
        - artiq


about:
    home: http://m-labs.hk/artiq
    license: 3-clause BSD
    summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
