package:
  name: artiq-kc705-nist_qc2
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/m-labs/artiq
  git_tag: master

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}

requirements:
  build:
    # We don't get meaningful GIT_DESCRIBE_* values until before conda installs build dependencies.
    - artiq 0.0
    - migen 0.0
    - misoc 0.0
    - llvm-or1k
    - binutils-or1k-linux
  run:
    - artiq 0.0

about:
  home: http://m-labs.hk/artiq
  license: GPL
  summary: 'Bitstream, BIOS and runtime for NIST_QC2 on the KC705 board'
