[package]
authors = ["M-Labs"]
name = "lwip"
version = "0.0.0"

[lib]
name = "lwip"
path = "lib.rs"

[dependencies]
lwip-sys = { path = "../liblwip-sys" }
std_artiq = { path = "../libstd_artiq", features = ["alloc"] }

[features]
default = ["preemption"]
preemption = []
