package:
    name: pycairo
    version: "1.10.0"

source:
    git_url: git://git.cairographics.org/git/pycairo
    git_tag: master

build:
    number: 2
    script: $PYTHON setup.py install

requirements:
    build:
        - python
        - setuptools
        - cairo 1.14.0 # [not win]
    run:
        - python
        - cairo 1.14.0 # [not win]

test:
    imports:
        - cairo

about:
    home: http://cairographics.org/pycairo/
    license: LGPL 3
    summary: 'Python 3 bindings for cairo'
