package:
  name: pyqtgraph
  version: "0.9.10"

source:
  fn: pyqtgraph-0.9.10.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqtgraph/pyqtgraph-0.9.10.tar.gz
  md5: bd84bf7537c43cf38db81cc1ad4f743a

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pyqt >=4.7

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT License
  summary: 'Scientific Graphics and GUI Library for Python'
