# This conda recipe is based on this one: https://github.com/tpn/trent-conda-recipes/tree/master/cairo

package:
    name: cairo
    version: 1.14.0
source:
    fn: cairo-1.14.0.tar.xz
    url: http://cairographics.org/releases/cairo-1.14.0.tar.xz
build:
    number: 0
requirements:
    build:
        - freetype
        - libpng
        - pixman >=0.30
        - zlib
    run:
        - freetype
        - libpng
        - pixman >=0.30
        - zlib
about:
    home: http://cairographics.org/
    license: LGPL 2.1 and MPL 1.1
# vim:set ts=8 sw=2 sts=2 tw=78 et:
